[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "markdown2>=2.5.3",
    "reportlab>=4.4.1",
    "requests>=2.32.3",
]
